# Generated by Django 3.1.5 on 2021-01-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210128_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='listing',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='ParentCategoryProductListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parentcategory')),
                ('product_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productlisting')),
            ],
            options={
                'unique_together': {('parent_category', 'product_listing')},
            },
        ),
        migrations.CreateModel(
            name='ProductProductListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcp_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parentcategoryproductlistings')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'pcp_listing')},
            },
        ),
    ]
