# Generated by Django 3.1.5 on 2021-01-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210128_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentCategoryProductListings',
            new_name='ParentCategoryProductListing',
        ),
    ]
