# Generated by Django 3.1.5 on 2021-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210128_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
