# Generated by Django 3.1.5 on 2021-02-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_qty'),
        ('order', '0002_job_transactionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
    ]
